### ISSUE TITLE
NotImplementedError in Binomial

### ISSUE THREAD

**Issue by kevindavisross** [dlsun/symbulate#18]
The following example returns an error.  It seems that there is an issue in distributions.py when n is not fixed for Binomial.  I'm not sure if this is just a problem for Binomial or other distributions.  A similar example with (Y | X = x) ~ Uniform(0, x) works fine.
 
def curry():
    FGA = Poisson(8.3).draw()  # 2 point field goals attempted
    FGM = Binomial(FGA, 0.54).draw()  # 2 point field goals made
    return FGA, FGM

FGA, FGM = RV(ProbabilitySpace(curry))
FGM.sim(10000).plot()

**Comment by dlsun** [comment]
That's because FGA is sometimes equal to 0, and Howard changed the code to raise NotImplementedError for a Binomial when n=0. (By the way, this is a _great_ example of why it's important to implement all the edge cases, like n=0, p=0, p=1, etc.)

@hliu26  Numpy seems to have no problem simulating a Binomial with n=0, and Scipy doesn't have any problem with it for the most part. The only problem that Scipy has (which is, I think, the reason you decided to raise the NotImplementedError) is with .ppf(), so maybe we should just override that one function. In any case, I would allow n=0 while we figure out what to do.

**Comment by kevindavisross** [comment]
I am going to close this issue and make a separate note regarding recoding to allow degenerate distributions.
